"""add ai_suggestion model

Revision ID: 84c9df68bbb4
Revises: 93455c90af6f
Create Date: 2026-03-31 12:55:53.782804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84c9df68bbb4'
down_revision: Union[str, None] = '93455c90af6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_application_id'), 'ai_suggestions', ['application_id'], unique=True)
    op.create_index(op.f('ix_ai_suggestions_id'), 'ai_suggestions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_suggestions_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_application_id'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
