"""add full application model with AI fields

Revision ID: 93455c90af6f
Revises: d23ee7441c95
Create Date: 2026-03-25 23:33:23.954630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '93455c90af6f'
down_revision: Union[str, None] = 'd23ee7441c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('applied_date', sa.Date(), nullable=True))
    op.add_column('job_applications', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('job_applications', sa.Column('jd_skills', sa.JSON(), nullable=True))
    op.add_column('job_applications', sa.Column('fit_score', sa.Float(), nullable=True))
    op.add_column('job_applications', sa.Column('fit_score_pct', sa.Integer(), nullable=True))
    op.add_column('job_applications', sa.Column('fit_label', sa.String(length=50), nullable=True))
    op.add_column('job_applications', sa.Column('semantic_score', sa.Float(), nullable=True))
    op.add_column('job_applications', sa.Column('skill_overlap_score', sa.Float(), nullable=True))
    op.add_column('job_applications', sa.Column('matched_skills', sa.JSON(), nullable=True))
    op.add_column('job_applications', sa.Column('missing_skills', sa.JSON(), nullable=True))
    op.alter_column('job_applications', 'company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('job_applications', 'job_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('job_applications', 'job_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('job_applications', 'application_date')
    op.drop_column('job_applications', 'is_remote')
    op.drop_column('job_applications', 'salary_max')
    op.drop_column('job_applications', 'location')
    op.drop_column('job_applications', 'salary_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('salary_min', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('job_applications', sa.Column('salary_max', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_applications', sa.Column('is_remote', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('job_applications', sa.Column('application_date', sa.DATE(), nullable=True))
    op.alter_column('job_applications', 'job_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('job_applications', 'job_title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
    op.alter_column('job_applications', 'company_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
    op.drop_column('job_applications', 'missing_skills')
    op.drop_column('job_applications', 'matched_skills')
    op.drop_column('job_applications', 'skill_overlap_score')
    op.drop_column('job_applications', 'semantic_score')
    op.drop_column('job_applications', 'fit_label')
    op.drop_column('job_applications', 'fit_score_pct')
    op.drop_column('job_applications', 'fit_score')
    op.drop_column('job_applications', 'jd_skills')
    op.drop_column('job_applications', 'notes')
    op.drop_column('job_applications', 'applied_date')
    # ### end Alembic commands ###
